"""Hypothesis data models."""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class HypothesisStatus(str, Enum):
    GENERATED = "generated"
    UNDER_CRITIQUE = "under_critique"
    SURVIVED_CRITIQUE = "survived_critique"
    TESTING = "testing"
    CONFIRMED = "confirmed"
    REFUTED = "refuted"
    STALE = "stale"
    PROMOTED = "promoted"


class FalsificationCriteria(BaseModel):
    description: str
    test_method: str
    expected_outcome_if_true: str
    expected_outcome_if_false: str


class Hypothesis(BaseModel):
    """A research hypothesis generated by the system."""

    id: str = ""
    entity_1: str
    relation: str
    entity_2: str
    conditions: str = ""
    confidence: float = Field(ge=0.0, le=1.0, default=0.5)
    status: HypothesisStatus = HypothesisStatus.GENERATED
    rationale: str = ""
    supporting_evidence: list[str] = Field(default_factory=list)
    counter_evidence: list[str] = Field(default_factory=list)
    falsification_criteria: list[FalsificationCriteria] = Field(default_factory=list)
    source_gap_id: str | None = None
    critique_history: list[dict[str, str]] = Field(default_factory=list)
    novelty_score: float = 0.0
    surprise_score: float = 0.0
    feasibility_score: float = 0.0
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    last_updated: datetime = Field(default_factory=datetime.utcnow)
    granularity: str = "medium"  # "high_risk", "medium", "incremental"
